apiVersion: v1
kind: Service
metadata:
  name: hello-world-v1
  labels:
    app: hello-world
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: hello-world
    version: v1.0.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-v1
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
      version: v1.0.0
  template:
    metadata:
      labels:
        app: hello-world
        version: v1.0.0
    spec:
      containers:
      - name: hello-world
        image: ahdepe/simple-web-app
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: VERSION
          value: v1.0.0